# Generated by Django 3.2.4 on 2022-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calismalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calismalar_title_bir', models.CharField(max_length=255)),
                ('calismalar_image_bir', models.ImageField(upload_to='', verbose_name='image_bir')),
                ('calismalar_title_iki', models.CharField(max_length=255)),
                ('calismalar_image_iki', models.ImageField(upload_to='', verbose_name='image_iki')),
                ('calismalar_title_uc', models.CharField(max_length=255)),
                ('calismalar_image_uc', models.ImageField(upload_to='', verbose_name='image_uc')),
            ],
        ),
        migrations.CreateModel(
            name='Hizmetlerimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_hizmetler_title', models.CharField(max_length=255, verbose_name='main-hizmetler-title')),
                ('hizmeler_bir', models.CharField(max_length=255)),
                ('hizmetler_bir_aciklama', models.TextField(verbose_name='hizmetler_bir_aciklama')),
                ('hizmeler_iki', models.CharField(max_length=255)),
                ('hizmetler_iki_aciklama', models.TextField(verbose_name='hizmetler_iki_aciklama')),
                ('hizmeler_uc', models.CharField(max_length=255)),
                ('hizmetler_uc_aciklama', models.TextField(verbose_name='hizmetler_uc_aciklama')),
                ('hizmeler_dort', models.CharField(max_length=255)),
                ('hizmetler_dort_aciklama', models.TextField(verbose_name='hizmetler_dort_aciklama')),
            ],
        ),
        migrations.CreateModel(
            name='Hizmetlermiz_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmetlerimiz_detail_bir', models.CharField(max_length=255)),
                ('hizmetlerimiz_detail_aciklama_bir', models.TextField(verbose_name='hizmetlerminiz_bir_text')),
                ('hizmetlerimi_detail_iki', models.CharField(max_length=255)),
                ('hizmetlerimiz_detail_aciklama_iki', models.TextField(verbose_name='hizmetlerminiz_iki_text')),
                ('hizmetlerimi_detail_uc', models.CharField(max_length=255)),
                ('hizmetlerimiz_detail_aciklama_uc', models.TextField(verbose_name='hizmetlerminiz_uc_text')),
                ('hizmetlerimi_detail_dort', models.CharField(max_length=255)),
                ('hizmetlerimiz_detail_aciklama_dort', models.TextField(verbose_name='hizmetlerminiz_dort_text')),
                ('hizmetlerimi_detail_bes', models.CharField(max_length=255)),
                ('hizmetlerimiz_detail_aciklama_bes', models.TextField(verbose_name='hizmetlerminiz_bes_text')),
                ('hizmetlerimi_detail_altı', models.CharField(max_length=255)),
                ('hizmetlerimiz_detail_aciklama_altı', models.TextField(verbose_name='hizmetlerminiz_altı_text')),
            ],
        ),
        migrations.CreateModel(
            name='Kurumsal_Aciklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurumsal_aciklama_title', models.CharField(max_length=255)),
                ('kurumsal_acikla_text', models.TextField(verbose_name='kurumsal_aciklama_text')),
                ('kurumsal_aciklama_bir', models.CharField(blank=True, max_length=255, null=True, verbose_name='kurumsal_aciklama_bir')),
                ('kurumsal_aciklama_iki', models.CharField(blank=True, max_length=255, null=True, verbose_name='kurumsal_aciklama_iki')),
                ('kurumsal_aciklama_uc', models.CharField(blank=True, max_length=255, null=True, verbose_name='kurumsal_aciklama_uc')),
                ('kurumsal_aciklama_dort', models.CharField(blank=True, max_length=255, null=True, verbose_name='kurumsal_aciklama_dort')),
                ('kurumsal_aciklama_bes', models.CharField(blank=True, max_length=255, null=True, verbose_name='kurumsal_aciklama_bes')),
                ('kurumsal_aciklama_alti', models.CharField(blank=True, max_length=255, null=True, verbose_name='kurumsal_aciklama_altı')),
            ],
        ),
        migrations.CreateModel(
            name='Musteri_Yorumları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_yorumlari_bir_resim', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('musteri_yorumlari_bir_aciklama', models.TextField(blank=True, null=True, verbose_name='musteri_yorumları_bir')),
                ('musteri_yorumlari_bir_title', models.CharField(max_length=100)),
                ('musteri_yorumlari_iki_resim', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('musteri_yorumlari_iki_aciklama', models.TextField(blank=True, null=True, verbose_name='musteri_yorumları_iki')),
                ('musteri_yorumlari_iki_title', models.CharField(max_length=100)),
                ('musteri_yorumlari_uc_resim', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('musteri_yorumlari_uc_aciklama', models.TextField(blank=True, null=True, verbose_name='musteri_yorumları_uc')),
                ('musteri_yorumlari_uc_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referanslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referans_bir', models.ImageField(blank=True, null=True, upload_to='', verbose_name='referans_image_bir')),
                ('referans_iki', models.ImageField(blank=True, null=True, upload_to='', verbose_name='referans_image_iki')),
                ('referans_uc', models.ImageField(blank=True, null=True, upload_to='', verbose_name='referans_image_uc')),
                ('referans_dort', models.ImageField(blank=True, null=True, upload_to='', verbose_name='referans_image_dort')),
                ('referans_bes', models.ImageField(blank=True, null=True, upload_to='', verbose_name='referans_image_bes')),
            ],
        ),
        migrations.CreateModel(
            name='Sayac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_sayac', models.IntegerField(default=0)),
                ('musteri_sayac', models.IntegerField(default=0)),
                ('referans_sayac', models.IntegerField(default=0)),
                ('uzman_sayac', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='slider-title')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='SıkcaSorulanSorular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SikcaSorulanSorular_bir', models.CharField(blank=True, max_length=255, null=True, verbose_name='SıkcaSorulanSorular_bir')),
                ('SikcaSorulanSorular_text_bir', models.TextField(blank=True, null=True, verbose_name='SıkcaSorulanSorular_bir')),
                ('SikcaSorulanSorular_iki', models.CharField(blank=True, max_length=255, null=True, verbose_name='SıkcaSorulanSorular_iki')),
                ('SikcaSorulanSorular_text_iki', models.TextField(blank=True, null=True, verbose_name='SıkcaSorulanSorular_iki')),
                ('SikcaSorulanSorular_uc', models.CharField(blank=True, max_length=255, null=True, verbose_name='SıkcaSorulanSorular_uc')),
                ('SikcaSorulanSorular_text_uc', models.TextField(blank=True, null=True, verbose_name='SıkcaSorulanSorular_uc')),
                ('SikcaSorulanSorular_dort', models.CharField(blank=True, max_length=255, null=True, verbose_name='SıkcaSorulanSorular_dort')),
                ('SikcaSorulanSorular_text_dort', models.TextField(blank=True, null=True, verbose_name='SıkcaSorulanSorular_dort')),
                ('SikcaSorulanSorular_bes', models.CharField(blank=True, max_length=255, null=True, verbose_name='SıkcaSorulanSorular_bes')),
                ('SikcaSorulanSorular_text_bes', models.TextField(blank=True, null=True, verbose_name='SıkcaSorulanSorular_bes')),
                ('SikcaSorulanSorular_alti', models.CharField(blank=True, max_length=255, null=True, verbose_name='SıkcaSorulanSorular_alti')),
                ('SikcaSorulanSorular_text_alti', models.TextField(blank=True, null=True, verbose_name='SıkcaSorulanSorular_alti')),
            ],
        ),
    ]
