# Generated by Django 3.2.4 on 2022-09-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hizmetlermiz_details',
            old_name='hizmetlerimi_detail_altı',
            new_name='hizmetlerimiz_detail_altı',
        ),
        migrations.RenameField(
            model_name='hizmetlermiz_details',
            old_name='hizmetlerimi_detail_bes',
            new_name='hizmetlerimiz_detail_bes',
        ),
        migrations.RenameField(
            model_name='hizmetlermiz_details',
            old_name='hizmetlerimi_detail_dort',
            new_name='hizmetlerimiz_detail_dort',
        ),
        migrations.RenameField(
            model_name='hizmetlermiz_details',
            old_name='hizmetlerimi_detail_iki',
            new_name='hizmetlerimiz_detail_iki',
        ),
        migrations.RenameField(
            model_name='hizmetlermiz_details',
            old_name='hizmetlerimi_detail_uc',
            new_name='hizmetlerimiz_detail_uc',
        ),
    ]
