# Generated by Django 3.2.4 on 2022-09-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0003_sosyal_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_bir_alti_dokuz',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_bir_alti_dokuz_right',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_iki_alti_yedi',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_uc_bes_dokuz',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
