# Generated by Django 3.2.4 on 2022-09-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0004_auto_20220918_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_iki_alti_yedi',
        ),
    ]
