# Generated by Django 3.2.4 on 2022-09-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0005_remove_kurumsal_aciklama_kurumsal_aciklama_image_iki_alti_yedi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_bir_alti_dokuz',
        ),
        migrations.RemoveField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_bir_alti_dokuz_right',
        ),
        migrations.RemoveField(
            model_name='kurumsal_aciklama',
            name='kurumsal_aciklama_image_uc_bes_dokuz',
        ),
    ]
