# Generated by Django 3.2.4 on 2022-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0007_kurumsal_aciklama_kurumsal_aciklama_image_uc_bes_dokuz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calismalar',
            options={'verbose_name': 'Çalışma', 'verbose_name_plural': 'Çalışmalar'},
        ),
        migrations.AlterModelOptions(
            name='hizmetlerimiz',
            options={'verbose_name_plural': 'Hizmetlerimiz'},
        ),
        migrations.AlterModelOptions(
            name='hizmetlermiz_details',
            options={'verbose_name': 'Hizmetlerimiz Açıklama', 'verbose_name_plural': 'Hizmetlerimiz Detail'},
        ),
        migrations.AlterModelOptions(
            name='kurumsal_aciklama',
            options={'verbose_name': 'Kurumsal Açıklama', 'verbose_name_plural': 'Kurumsal Açıklamalar'},
        ),
        migrations.AlterModelOptions(
            name='musteri_yorumları',
            options={'verbose_name': 'Müşteri Yorumlar', 'verbose_name_plural': 'Müşteri Yorumları'},
        ),
        migrations.AlterModelOptions(
            name='referanslar',
            options={'verbose_name': 'Referans', 'verbose_name_plural': 'Referanslar'},
        ),
        migrations.AlterModelOptions(
            name='sayac',
            options={'verbose_name_plural': 'Sayac'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sitenin En Üstü'},
        ),
        migrations.AlterModelOptions(
            name='sosyal_media',
            options={'verbose_name': 'Sosyal Medya', 'verbose_name_plural': 'Sosyal Medyalar'},
        ),
        migrations.AlterModelOptions(
            name='sıkcasorulansorular',
            options={'verbose_name': 'S.S.S', 'verbose_name_plural': 'Sıkca Sorulan Sorular'},
        ),
        migrations.AddField(
            model_name='calismalar',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calismalar',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hizmetlerimiz',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hizmetlerimiz',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hizmetlermiz_details',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hizmetlermiz_details',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kurumsal_aciklama',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kurumsal_aciklama',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='musteri_yorumları',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='musteri_yorumları',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='referanslar',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='referanslar',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sayac',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sayac',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyal_media',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyal_media',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sıkcasorulansorular',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sıkcasorulansorular',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
