# Generated by Django 3.2.4 on 2022-09-24 14:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0008_auto_20220924_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='hizmetler_bir_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='hizmetler_dort_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='hizmetler_iki_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='hizmetler_uc_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlermiz_details',
            name='hizmetlerimiz_detail_aciklama_altı',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlermiz_details',
            name='hizmetlerimiz_detail_aciklama_bes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlermiz_details',
            name='hizmetlerimiz_detail_aciklama_bir',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlermiz_details',
            name='hizmetlerimiz_detail_aciklama_dort',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlermiz_details',
            name='hizmetlerimiz_detail_aciklama_iki',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmetlermiz_details',
            name='hizmetlerimiz_detail_aciklama_uc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kurumsal_aciklama',
            name='kurumsal_acikla_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='musteri_yorumları',
            name='musteri_yorumlari_bir_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musteri_yorumları',
            name='musteri_yorumlari_iki_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musteri_yorumları',
            name='musteri_yorumlari_uc_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sıkcasorulansorular',
            name='SikcaSorulanSorular_text_alti',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sıkcasorulansorular',
            name='SikcaSorulanSorular_text_bes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sıkcasorulansorular',
            name='SikcaSorulanSorular_text_bir',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sıkcasorulansorular',
            name='SikcaSorulanSorular_text_dort',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sıkcasorulansorular',
            name='SikcaSorulanSorular_text_iki',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sıkcasorulansorular',
            name='SikcaSorulanSorular_text_uc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
